<?php

module_load_include('inc', 'link_checker', 'includes/check_url');
module_load_include('inc', 'link_checker', 'includes/extract_urls');

/**
 * Implements hook_theme().
 */
function link_checker_theme($existing, $type, $theme, $path) {
    return array (
        'link_report' => array(
            'variables' => array(
                'url_report' => array(),
                'url_report_queue'=> array(),
                'stats' => array())
        )
    );
}
